### ISSUE TITLE
some problems with line breaks in putty

### ISSUE THREAD

**Issue by pikasTech** [maxgerhardt/pikascript-pio-bluepill#4]
The amazing news is that a tuber tried this demo on his stm32f103c8.

https://www.youtube.com/watch?v=91xyL0ryVJg&t=143s

![image](https://user-images.githubusercontent.com/88232613/170169471-ab8c0e36-68eb-4a7b-9947-96d9f1e7ed9d.png)

But it looks like this demo has some problems with line breaks in putty.

![image](https://user-images.githubusercontent.com/88232613/170169416-f32de8a8-036d-4a26-b312-ffc9c442360d.png)

Do you have any suggestions on this issue, perhaps a problem with the putty settings?

**Comment by maxgerhardt** [comment]
I've noticed this too. I expected people to use the "Monitor" task in the PlatformIO sidebar (alien icon on the left) which opens miniterm.py which sets 

https://github.com/maxgerhardt/pikascript-pio-bluepill/blob/dda44fa3fcc5e72d769994ce1a44d517b7664092/platformio.ini#L33-L35

line ending to `\n` (LF). If putty is using `\r\n` (CRLF) or CR, things are not correct.

I have to look closer on why that is.
